import { Variant, VARIANTS } from "../const";
import { generateDateTimeString } from "../utils";

const OVPN_TEMPLATE = `# Generated by Nasu VPN Checker (https://umavpn.top) at %TIME%

dev tun
proto %PROTO%
remote %IP% %PORT%
cipher AES-128-CBC
data-ciphers AES-128-CBC
auth SHA1
resolv-retry infinite
nobind
persist-key
persist-tun
client
verb 3

<ca>
%CA%
</ca>

<cert>
%CERT%
</cert>

<key>
%KEY%
</key>
`;

const ROUTE_PATCH = `

# Route patch
route-nopull

route api-umamusume.cygames.jp
route prd-storage-app-umamusume.akamaized.net
route prd-storage-game-umamusume.akamaized.net
route prd-info-umamusume.akamaized.net

route apidgp-gameplayer.games.dmm.com
`.replaceAll("\n", "\r\n");

const DNS_PATCH = `

# DNS patch (Beta)
dns search-domains api-umamusume.cygames.jp
dns search-domains prd-storage-app-umamusume.akamaized.net
dns search-domains prd-storage-game-umamusume.akamaized.net
dns search-domains prd-info-umamusume.akamaized.net

dns search-domains apidgp-gameplayer.games.dmm.com
`.replaceAll("\n", "\r\n");

export class OVPNBuilder {
    #time!: string;
    #proto!: string;
    #ip!: string;
    #port!: number;
    #ca!: string;
    #cert!: string;
    #key!: string;

    #getVariantShortCode(variant: Variant) {
        return {
            legacy: "L",
            current: "C",
            beta: "B"
        }[variant];
    }

    #getTypeShortCode(split?: string) {
        return typeof split !== "undefined" ? "S" : "O";
    }
    
    public setTime(time: string) {
        this.#time = time;
        return this;
    }

    public setProto(proto: string) {
        this.#proto = proto;
        return this;
    }

    public setIp(ip: string) {
        this.#ip = ip;
        return this;
    }

    public setPort(port: number) {
        this.#port = port;
        return this;
    }

    public setCa(ca: string) {
        this.#ca = ca;
        return this;
    }

    public setCert(cert: string) {
        this.#cert = cert;
        return this;
    }

    public setKey(key: string) {
        this.#key = key;
        return this;
    }

    public build(variant: Variant, split?: string) {
        let config = OVPN_TEMPLATE
            .replace("%TIME%", this.#time)
            .replace("%PROTO%", this.#proto)
            .replace("%IP%", this.#ip)
            .replace("%PORT%", this.#port.toString())
            .replace("%CA%", this.#ca)
            .replace("%CERT%", this.#cert)
            .replace("%KEY%", this.#key);

        if (variant === "legacy") {
            // Remove line starts with "data-ciphers"
            config = config.replace(/^data-ciphers.+\n/m, "");
        }

        if (typeof split !== "undefined") {
            if (variant === "beta") {
                config += DNS_PATCH;
            }
            config += ROUTE_PATCH;
        }

        return {
            filename: `NasuVPN-${generateDateTimeString()}-${this.#ip}-${this.#getVariantShortCode(variant)}${this.#getTypeShortCode(split)}.ovpn`,
            content: config
        };
    }
}