export const SITES = [
    "uma",
    "dmm",
    "umag"
] as const;

export type Site = typeof SITES[number];

export const VARIANTS = [
    "legacy",
    "current",
    "beta"
];

export const OVPN_TEMPLATE = `
# Generated by Nasu VPN Checker (https://umavpn.pro) at %TIME%

dev tun
proto %PROTO%
remote %IP% %PORT%
cipher AES-128-CBC
data-ciphers AES-128-CBC
auth SHA1
resolv-retry infinite
nobind
persist-key
persist-tun
client
verb 3

<ca>
%CA%
</ca>

<cert>
%CERT%
</cert>

<key>
%KEY%
`;

export const CURRENT_PATCH = `

# Split tunneling patch
route-nopull

route api-umamusume.cygames.jp
route prd-storage-umamusume.akamaized.net
route prd-storage-app-umamusume.akamaized.net
route prd-storage-game-umamusume.akamaized.net
route prd-info-umamusume.akamaized.net

route apidgp-gameplayer.games.dmm.com
`.replaceAll("\n", "\r\n");

export const BETA_PATCH = `

# Split tunneling patch (Beta)
dns search-domains api-umamusume.cygames.jp
dns search-domains prd-storage-umamusume.akamaized.net
dns search-domains prd-storage-app-umamusume.akamaized.net
dns search-domains prd-storage-game-umamusume.akamaized.net
dns search-domains prd-info-umamusume.akamaized.net

dns search-domains apidgp-gameplayer.games.dmm.com
`.replaceAll("\n", "\r\n") + CURRENT_PATCH;