export const SITES = [
    "uma",
    "dmm"
] as const;

export type Site = typeof SITES[number];

export const VARIANTS = [
    "legacy",
    "current"
];

export const OVPN_TEMPLATE = `
# Generated by Nasu VPN Checker (https://umavpn.pro) at %TIME%

dev tun
proto %PROTO%
remote %IP% %PORT%
cipher AES-128-CBC
data-ciphers AES-128-CBC
auth SHA1
resolv-retry infinite
nobind
persist-key
persist-tun
client
verb 3

<ca>
%CA%
</ca>

<cert>
%CERT%
</cert>

<key>
%KEY%
</key>
`.replaceAll("\n", "\r\n");

export const PATCH = `
# Split tunneling patch
route-nopull

route api-umamusume.cygames.jp
route prd-storage-umamusume.akamaized.net
route prd-storage-app-umamusume.akamaized.net
route prd-storage-game-umamusume.akamaized.net
route prd-info-umamusume.akamaized.net

route apidgp-gameplayer.games.dmm.com
`.replaceAll("\n", "\r\n");